#!/usr/bin/python3


import os
import sys

def compile_python_file(pyfile):
    try:
        compiled_filename = pyfile + "c"
        os.system(f"python -m py_compile {pyfile}")
        print(f"Compiled {pyfile} successfully. Output filename: {compiled_filename}")
    except Exception as e:
        print(f"Error compiling {pyfile}: {e}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python compile_script.py <python_file.py>")
        sys.exit(1)

    pyfile = sys.argv[1]
    compile_python_file(pyfile)
